Improved mongodb template

diff --git a/.templates/mongodb-files/service.template b/.templates/mongodb-files/service.template
--- a/.templates/mongodb-files/service.template
+++ b/.templates/mongodb-files/service.template
@@ -3,6 +3,8 @@
 # api: public
 # txt: Launches MongoDB
 
+export DW_DISABLE_ANSI_COLORS=TRUE;
+
 DW.import mongodb;
 
 # fun: main
@@ -24,30 +26,43 @@ function main() {
   done;
   IFS="${_oldIFS}";
 
-  if fileExists "${BOOTSTRAP_FILE}"; then
+  local -i _runMongod=${TRUE};
 
-    if isEmpty "${SQ_AUTHENTICATION_MECHANISM}"; then
-      logInfo "Launching MongoDB with no authentication"
-      startMongodWithAuthenticationDisabled ${SERVICE_USER} ${SERVICE_GROUP} "${DB_FOLDER}" "${MONGOD_CONFIG_FILE}";
-    else
-      logInfo "Launching MongoDB with ${SQ_AUTHENTICATION_MECHANISM} authentication mechanism"
-      startMongodWithAuthenticationEnabled ${SERVICE_USER} ${SERVICE_GROUP} "${DB_FOLDER}" "${MONGOD_CONFIG_FILE}" "${SQ_AUTHENTICATION_MECHANISM}";
-    fi
-  else
-    while ! fileExists "${BOOTSTRAP_FILE}"; do
-      logInfo -n "Waiting ${SLEEP}s for the bootstrap process to finish";
-      sleep ${SLEEP};
-      logInfoResult SUCCESS "done";
-    done
+  local -i _bootstrapNeeded=${TRUE};
+  if     ! fileExists "${BOOTSTRAP_FILE}" \
+      && fileExists /usr/local/bin/${IMAGE}-bootstrap.sh; then
+    _bootstrapNeeded=${TRUE};
+  fi
 
-    if fileExists "${BOOTSTRAP_FILE}"; then
+  if isTrue ${_bootstrapNeeded}; then
+    /usr/local/bin/${IMAGE}-bootstrap.sh -v;
+    local _rescode=$?;
+    if isTrue ${_rescode}; then
       logInfo -n "Bootstrap completed";
       logInfoResult SUCCESS "done";
+    else
+      logInfo -n "Bootstrap failed";
+      logInfoResult FAILURE "failed";
+      _runMongod=${FALSE};
+    fi
+  fi
+
+  if isTrue ${_runMongod}; then
+    if isEmpty "${SQ_AUTHENTICATION_MECHANISM}"; then
+      logInfo "Launching MongoDB with no authentication";
+      startMongodWithAuthenticationDisabled ${SERVICE_USER} ${SERVICE_GROUP} "${DB_FOLDER}" "${MONGOD_CONFIG_FILE}";
+    else
+      logInfo "Launching MongoDB with ${SQ_AUTHENTICATION_MECHANISM} authentication mechanism";
+      startMongodWithAuthenticationEnabled ${SERVICE_USER} ${SERVICE_GROUP} "${DB_FOLDER}" "${MONGOD_CONFIG_FILE}" "${SQ_AUTHENTICATION_MECHANISM}";
     fi
 
-    while fileExists "${BOOTSTRAP_FILE}"; do
+    tail -f "${MONGOD_LOG_FILE}" &
+
+    while isMongodRunning; do
       sleep ${SLEEP};
     done
+  else
+    logInfo "Cannot run MongoDB since the bootstrap process failed";
   fi
 }
 
@@ -56,5 +71,6 @@ setScriptDescription "Launches MongoDB";
 defineEnvVar DB_FOLDER OPTIONAL "The database folder" "/backup/mongodb/db";
 defineEnvVar BOOTSTRAP_FILE OPTIONAL "The bootstrap file" "{DB_FOLDER}/.bootstrapped";
 defineEnvVar MONGOD_CONFIG_FILE OPTIONAL "The mongod config file" "/etc/mongod.conf";
-defineEnvVar SLEEP OPTIONAL "The number of seconds to wait before checking if the bootstrap process has finished" 10;
+defineEnvVar MONGOD_LOG_FILE OPTIONAL "The mongod log file" "/var/log/mongodb/mongod.log";
+defineEnvVar SLEEP OPTIONAL "The number of seconds to sleep before checking in mongod is running again" 300;
 # vim: syntax=sh ts=2 sw=2 sts=4 sr noet
