Added more environment properties to take care of in gradle image

diff --git a/gradle/my_exec.template b/gradle/my_exec.template
--- a/gradle/my_exec.template
+++ b/gradle/my_exec.template
@@ -22,5 +22,22 @@ if [ -n "${_dockerApiVersion}" ]; then
   _dockerApiVersion="-DAPI_VERSION=${_dockerApiVersion} -Dapi.version=${_dockerApiVersion} -DDOCKER_API_VERSION=${_dockerApiVersion}"
 fi
 
-/usr/local/bin/run-as.sh -- ${_projectFolder} gradle -g /opt/workspace/.gradle -DDOCKER_HOST=${_dockerHost} -DHOST_PROJECTDIR=${HOST_PROJECTDIR:-${_folder}} -DHOST_USERHOME=${HOST_USERHOME:-${HOME}} ${_dockerApiVersion} ${_cmd};
+_gradleTag="${GRADLE_TAG:-${TAG}}";
+if [ -n "${_gradleTag}" ]; then
+  _gradleTag="-DGRADLE_TAG=\"${_gradleTag}\"";
+fi
+_grailsTag="${GRAILS_TAG:-${TAG}}";
+if [ -n "${_grailsTag}" ]; then
+  _grailsTag="-DGRAILS_TAG=\"${_grailsTag}\"";
+fi
+_nodeJsTag="${NODEJS_TAG:-${TAG}}";
+if [ -n "${_nodeJsTag}" ]; then
+  _nodeJsTag="-DNODEJS_TAG=\"${_nodeJsTag}\"";
+fi
+
+exec /usr/local/bin/run-as.sh -- ${_projectFolder} gradle -g /opt/workspace/.gradle -DDOCKER_HOST=${_dockerHost} -DHOST_PROJECTDIR=${HOST_PROJECTDIR:-${_folder}} -DHOST_USERHOME=${HOST_USERHOME:-${HOME}} ${_dockerApiVersion} ${_gradleTag} ${_grailsTag} ${_nodeJsTag} ${_cmd};
+_rescode=$?
+if [ ${_rescode} -ne 0 ]; then
+  echo "Returning error code ${_rescode}";
+fi
 # vim: syntax=sh ts=4 sw=4 sts=4 sr noet
