Updated MongoDB images (2.6.12 and 3.4.2)

diff --git a/mongodb/service.template b/mongodb/service.template
--- a/mongodb/service.template
+++ b/mongodb/service.template
@@ -1,5 +1,35 @@
 #!/bin/bash
 
+mkdir -p /backup/${IMAGE}/db
+rsync -az /backup/${IMAGE}/db/ /var/lib/mongodb/
+rsync -az /var/lib/mongodb/ /backup/${IMAGE}/db/
+chown -R ${SERVICE_USER}:${SERVICE_GROUP} /var/lib/mongodb /var/log/mongodb
+
+_alive=1;
+
+if [ ! -e /backup/${IMAGE}/db/.bootstrapped ]; then
+    /usr/local/bin/run-as.sh -U ${SERVICE_USER} -G ${SERVICE_GROUP} -- /backup/${IMAGE}/db /usr/bin/mongod --config /etc/mongod.conf $@ &
+    ps -ef | grep mongodb | grep -v grep | grep -v bootstrap | grep -v service > /dev/null
+    _alive=$?;
+    while [ ${_alive} -eq 0 ] && [ ! -e /backup/${IMAGE}/db/.bootstrapped ]; do
+      /usr/local/bin/${SQ_IMAGE}-bootstrap.sh
+      echo "We'll try to bootstrap Mongo again in 1s";
+      sleep 1s;
+      ps -ef | grep mongodb | grep -v grep | grep -v bootstrap | grep -v service > /dev/null
+      _alive=$?;
+    done
+fi
+
+if [ ${_alive} -ne 0 ]; then
+    echo "Could not bootstrap MongoDB"
+    exit 1
+else
+  exec /usr/local/bin/run-as.sh -U ${SERVICE_USER} -G ${SERVICE_GROUP} -- /backup/${IMAGE}/db /usr/bin/mongod --config /etc/mongod.conf --auth $@
+fi
+
+
+#!/bin/bash
+
 rsync -az /backup/${IMAGE}/db/ /var/lib/mongodb/
 rsync -az /var/lib/mongodb/ /backup/${IMAGE}/db/
 
