WIP mongodb startup script

diff --git a/mongodb/service.template b/mongodb/service.template
--- a/mongodb/service.template
+++ b/mongodb/service.template
@@ -1,14 +1,22 @@
 #!/bin/bash
 
-_bootstrapFile="/backup/${IMAGE}/db/.bootstrapped";
+_bootstrapFile="/backup/mongodb/db/.bootstrapped";
 
-mkdir -p /backup/${IMAGE}/db
-rsync -az /backup/${IMAGE}/db/ /var/lib/mongodb/
-rsync -az /var/lib/mongodb/ /backup/${IMAGE}/db/
-chown -R ${SERVICE_USER}:${SERVICE_GROUP} /var/lib/mongodb /var/log/mongodb
+mkdir -p /backup/mongodb/db
+rsync -az /backup/mongodb/db/ /var/lib/mongodb/
+rsync -az /var/lib/mongodb/ /backup/mongodb/db/
+chown -R mongodb:mongodb /var/lib/mongodb /var/log/mongodb
 
 if [ ! -e ${_bootstrapFile} ]; then
-    /usr/local/bin/run-as.sh -U ${SERVICE_USER} -G ${SERVICE_GROUP} -- /backup/${IMAGE}/db /usr/bin/mongod --config /etc/mongod.conf $@ &
+    jobs &>/dev/null
+    /usr/local/bin/run-as.sh -U mongodb -G mongodb -- /backup/mongodb/db /usr/bin/mongod --config /etc/mongod.conf $@ > /dev/null 2>&1 &
+    mongoStarted="$(jobs -n)"
+    if [ -n "${mongoStarted}" ];then
+      mongoPid=$!;
+    else
+      echo "Could not launch MongoDB for bootstrap"
+      exit 1;
+    fi
     ps -ef | grep mongodb | grep -v grep | grep -v bootstrap | grep -v service > /dev/null
     _alive=$?;
     while [ ${_alive} -eq 0 ] && [ ! -e ${_bootstrapFile} ]; do
@@ -18,10 +26,23 @@ if [ ! -e ${_bootstrapFile} ]; then
       ps -ef | grep mongodb | grep -v grep | grep -v bootstrap | grep -v service > /dev/null
       _alive=$?;
     done
-fi
+    echo -n "Waiting MongoDB to shut down ";
+    kill ${mongoPid}
+    ps -ef | grep mongodb | grep -v grep | grep -v bootstrap | grep -v service > /dev/null
+    _alive=$?;
+    while [ ${_alive} -eq 0 ]; do
+      echo ".";
+      sleep 1s;
+      ps -f -p ${mongoPid} > /dev/null
+      _alive=$?;
+    done
+    rm -f /backup/mongodb/db/mongod.lock
+    echo "";
+ fi
 
 if [ -e ${_bootstrapFile} ]; then
-    exec /usr/local/bin/run-as.sh -U ${SERVICE_USER} -G ${SERVICE_GROUP} -- /backup/${IMAGE}/db /usr/bin/mongod --config /etc/mongod.conf --auth $@
+    echo "Launching MongoDB"
+    exec /usr/local/bin/run-as.sh -U mongodb -G mongodb -- /backup/mongodb/db /usr/bin/mongod --config /etc/mongod.conf --auth $@
 else
   echo "Could not bootstrap MongoDB"
   exit 1
