Work on gradle-gtoolkit-TexLive image

diff --git a/.templates/sdkman.template b/.templates/sdkman.template
--- a/.templates/sdkman.template
+++ b/.templates/sdkman.template
@@ -1,4 +1,3 @@
 # v sdkman
-RUN su - ${SERVICE_USER} -c 'cd ${SERVICE_USER_HOME} && (wget -q -O- http://get.sdkman.io | bash || (echo "sdkman zeroconf failed") \
- && chmod +x ${SERVICE_USER_HOME}/.sdkman/bin/sdkman-init.sh || echo "chmod failed")'
+RUN su - ${SERVICE_USER} -c 'cd ${SERVICE_USER_HOME} && (wget -q -O- http://get.sdkman.io | bash || (echo "sdkman zeroconf failed") && chmod +x ${SERVICE_USER_HOME}/.sdkman/bin/sdkman-init.sh || echo "chmod failed")'
 # ^ sdkman
