Fixed jenkins plugins. Working on Nexus 3.1 and ElasticSearch images

diff --git a/.templates/service_user.template b/.templates/service_user.template
--- a/.templates/service_user.template
+++ b/.templates/service_user.template
@@ -1,9 +1,10 @@
-# service_user template
+# v service_user template
 ENV SERVICE_USER=${SERVICE_USER} \
     SERVICE_GROUP=${SERVICE_GROUP} \
     SERVICE_USER_SHELL=${SERVICE_USER_SHELL} \
     SERVICE_USER_HOME=${SERVICE_USER_HOME}
 
-RUN (/usr/sbin/groupadd ${SERVICE_GROUP} 2> /dev/null || echo "Group ${SERVICE_GROUP} already exists") && \
-    (/usr/sbin/useradd -m -g ${SERVICE_GROUP} -G ${SERVICE_GROUP} -d ${SERVICE_USER_HOME} -s ${SERVICE_USER_SHELL} -c "${IMAGE} user" ${SERVICE_USER} 2> /dev/null || echo "User ${SERVICE_USER} already exists")
-# end of service_user template
+RUN /usr/sbin/groupadd ${SERVICE_GROUP} && \
+    (mkdir -p $(dirname ${SERVICE_USER_HOME}) || echo "Skipping error") && \
+    /usr/sbin/useradd -m -g ${SERVICE_GROUP} -G ${SERVICE_GROUP} -d ${SERVICE_USER_HOME} -s ${SERVICE_USER_SHELL} -c "${IMAGE} user" ${SERVICE_USER}
+# ^ service_user template
