Improved MariaDB image

diff --git a/mariadb/bootstrap-db.template b/mariadb/bootstrap-db.template
--- a/mariadb/bootstrap-db.template
+++ b/mariadb/bootstrap-db.template
@@ -6,43 +6,117 @@
 # txt: Returns 0/TRUE always.
 # use: main
 function main() {
-  # Just in case Monit is configured to restart MariaDB
-  stop_monit;
 
-  wait_until_mariadb_stops ${SLEEP} "${MARIADB_ROOT_PASSWORD}";
+  local -i _monitRunning=${FALSE};
 
-  install_mariadb_db "${DATA_DIR}";
+  if is_monit_running; then
+    _monitRunning=${TRUE};
 
-  start_mariadb "${DATA_DIR}" "${SERVICE_USER}";
-
-  wait_until_mariadb_starts "${SLEEP}";
-
-  process_setup_file "${BOOTSTRAP_SETUP_FILE}";
-
-  run_sql_file "${BOOTSTRAP_SETUP_FILE}";
-
-  if folderExists "${BOOTSTRAP_SQL_FOLDER}"; then
-    local _oldIFS="${IFS}";
-    IFS="${DWIFS}";
-    local _file;
-    for _file in $(ls "${BOOTSTRAP_SQL_FOLDER}"/*.sql); do
-      IFS="${_oldIFS}";
-      run_sql_file "${_file}" "${MARIADB_ROOT_PASSWORD}";
-    done
-    IFS="${_oldIFS}";
+    # Just in case Monit is configured to restart MariaDB
+    stop_monit;
   fi
 
-  upgrade_mariadb "${MARIADB_ROOT_PASSWORD}";
+  wait_until_mariadb_stops ${SLEEP} "${ROOT_PASSWORD}";
 
-  shutdown_mariadb "${MARIADB_ROOT_PASSWORD}";
+  local -i _bootstrapFailed=${FALSE};
 
-  wait_until_mariadb_stops ${SLEEP} "${MARIADB_ROOT_PASSWORD}";
+  if ! install_mariadb_db "${DATA_DIR}"; then
+    _bootstrapFailed=${TRUE};
+  fi
 
-  process_data_folder "${DATA_DIR}" "${SERVICE_USER}" "${SERVICE_GROUP}";
+  if isFalse ${_bootstrapFailed}; then
+    if ! start_mariadb "${DATA_DIR}" "${MARIADB_USER}"; then
+      _bootstrapFailed=${TRUE};
+    fi
+  fi
 
-  mark_db_as_bootstrapped "${DATA_DIR}" "${BOOTSTRAP_MARK_FILE}";
+  if isFalse ${_bootstrapFailed}; then
+    if ! wait_until_mariadb_starts "${SLEEP}"; then
+      _bootstrapFailed=${TRUE};
+    fi
+  fi
 
-  start_monit;
+  if isFalse ${_bootstrapFailed}; then
+    if ! process_setup_file "${BOOTSTRAP_SETUP_FILE}"; then
+      _bootstrapFailed=${TRUE};
+    fi
+  fi
+
+  if isFalse ${_bootstrapFailed}; then
+
+    if ! run_sql_file "${BOOTSTRAP_SETUP_FILE}"; then
+      _bootstrapFailed=${TRUE};
+    fi
+  fi
+
+  if isFalse ${_bootstrapFailed}; then
+    if folderExists "${BOOTSTRAP_SQL_FOLDER}"; then
+      local _oldIFS="${IFS}";
+      IFS="${DWIFS}";
+      local _file;
+      for _file in $(ls "${BOOTSTRAP_SQL_FOLDER}"/*.sql); do
+        IFS="${_oldIFS}";
+        # if ! sanitize_sql_file "${_file}"; then
+        if ! run_sql_file "${_file}" "${ROOT_PASSWORD}"; then
+          _bootstrapFailed=${TRUE};
+          break;
+        fi
+      done
+      IFS="${_oldIFS}";
+    fi
+  fi
+
+  if isFalse ${_bootstrapFailed}; then
+    if ! upgrade_mariadb "${ROOT_PASSWORD}"; then
+      _bootstrapFailed=${TRUE};
+    fi
+  fi
+
+  if isFalse ${_bootstrapFailed}; then
+    shutdown_mariadb "${ROOT_PASSWORD}";
+  fi
+
+  if isFalse ${_bootstrapFailed}; then
+    if ! wait_until_mariadb_stops ${SLEEP} "${ROOT_PASSWORD}"; then
+      _bootstrapFailed=${TRUE};
+    fi
+  fi
+
+  if isFalse ${_bootstrapFailed}; then
+    if ! process_data_folder "${DATA_DIR}" "${MARIADB_USER}" "${MARIADB_GROUP}"; then
+      _bootstrapFailed=${TRUE};
+    fi
+  fi
+
+  if isFalse ${_bootstrapFailed}; then
+    mark_db_as_bootstrapped "${BOOTSTRAP_SUCCESS_MARK_FILE}";
+  else
+    mark_db_as_bootstrapped "${BOOTSTRAP_FAILURE_MARK_FILE}";
+  fi
+
+  if isTrue ${_monitRunning}; then
+    start_monit;
+  fi
+}
+
+# fun: is_monit_running
+# api: public
+# txt: Checks whether Monit is running.
+# txt: Returns 0/TRUE if Monit is running; 1/FALSE otherwise.
+# use: if is_monit_running; then echo "Monit is running"; fi
+function is_monit_running() {
+  local -i _rescode;
+
+  ps -ef | grep monit | grep -v grep > /dev/null 2>&1;
+  local -i _notRunning=$?;
+
+  if isTrue ${_notRunning}; then
+    _rescode=${FALSE};
+  else
+    _rescode=${TRUE};
+  fi
+
+  return ${_rescode};
 }
 
 # fun: stop_monit
@@ -51,7 +125,16 @@ function main() {
 # txt: Returns 0/TRUE if Monit is stops successfully.
 # use: if stop_monit; then echo "Monit stopped";
 function stop_monit() {
-  service monit stop;
+  logInfo -n "Stopping Monit";
+  service monit stop > /dev/null 2>&1;
+  local -i _rescode=$?;
+  if isTrue ${_rescode}; then
+    logDebugResult SUCCESS "done";
+  else
+    logDebugResult FAILURE "failed";
+  fi
+
+  return ${_rescode};
 }
 
 # fun: start_monit
@@ -60,7 +143,29 @@ function stop_monit() {
 # txt: Returns 0/TRUE if Monit starts.
 # use: if start_monit; then echo "Monit started successfully"; fi
 function start_monit() {
-  service monit start;
+  logInfo -n "Starting Monit";
+  service monit start > /dev/null 2>&1;
+  local -i _rescode=$?;
+  if isTrue ${_rescode}; then
+    logDebugResult SUCCESS "done";
+  else
+    logDebugResult FAILURE "failed";
+  fi
+
+  return ${_rescode};
+}
+
+# fun: is_mariadb_up
+# api: public
+# txt: Checks whether MariaDB is running.
+# txt: Returns 0/TRUE if MariaDB is running; 1/FALSE otherwise.
+# use: is_mariadb_up;
+function is_mariadb_up() {
+
+  netstat -putadon | grep ':3306' > /dev/null;
+  local -i _rescode=$?;
+
+  return ${_rescode};
 }
 
 # fun: wait_until_mariadb_stops sleep rootPassword
@@ -77,32 +182,29 @@ function wait_until_mariadb_stops() {
   local _password="${2}";
   checkNotEmpty rootPassword "${_password}" 2;
 
-  local -i _rescode=${TRUE};
+  local -i _rescode;
 
-  netstat -putadon | grep ':3306' > /dev/null;
-  local -i _alive=$?;
+  while is_mariadb_up; do
+    logInfo -n "Waiting ${_sleep}s for MariaDB to shut down";
+    sleep ${_sleep};
+    logInfoResult SUCCESS "done";
 
-  while isTrue ${_alive}; do
-    logInfo -n "Shutting MariaDB down";
+    logInfo -n "Trying to shut MariaDB down";
     if shutdown_mariadb "${_password}"; then
       logInfoResult SUCCESS "done";
-      logInfo -n "Waiting ${_sleep}s for MariaDB to shut down before trying again";
-      sleep ${_sleep};
-      logInfoResult SUCCESS "done";
-      netstat -putadon | grep ':3306' > /dev/null;
-      _alive=$?;
     else
-      logInfoResult SUCCESS "failed";
-      break;
+      logInfoResult FAILURE "failed";
     fi
   done
 
-  if isFalse ${_alive}; then
+  if is_mariadb_up; then
+    _rescode=${FALSE};
+  else
     _rescode=${TRUE};
   fi
 
-  if isFalse ${_rescode}; then
-    logInfo "MariaDB is not running";
+  if isTrue ${_rescode}; then
+    logInfo "MariaDB is NOT running";
   fi
 
   return ${_rescode};
@@ -118,19 +220,17 @@ function wait_until_mariadb_starts() {
   local _sleep="${1}";
   checkNotEmpty sleep "${_sleep}" 1;
 
-  netstat -putadon | grep ':3306' > /dev/null;
-  local -i _rescode=$?;
+  local -i _rescode=${FALSE};
 
-  while isFalse ${_rescode}; do
+  while ! is_mariadb_up; do
     logInfo -n "Waiting ${_sleep}s for MariaDB to boot";
     sleep ${_sleep};
     logInfoResult SUCCESS "done";
-    netstat -putadon | grep ':3306' > /dev/null;
-    _rescode=$?;
   done
 
-  if isTrue ${_rescode}; then
+  if is_mariadb_up; then
     logInfo "MariaDB up and running";
+    _rescode=${TRUE};
   fi
 
   return ${_rescode};
@@ -146,13 +246,13 @@ function process_setup_file() {
   local _file="${1}";
   checkNotEmpty file "${_file}" 1;
 
-  local -i _rescode;
-
   logDebug -n "Finding out own IP";
-  local _ip="$(ifconfig eth0 | grep 'inet addr' | cut -d':' -f 2 | awk '{print $1;}' | awk -F'.' '{printf("%d.%d.%d.%%\n", $1, $2, $3);}')";
-  _rescode=$?;
+  DW.import net;
+  retrieveOwnIp;
+  local -i _rescode=$?;
+  local _ip="${RESULT}";
 
-  if isTrue ${_rescode}; then
+  if isTrue ${_rescode} && ! isEmpty "${_ip}"; then
     logDebugResult SUCCESS "${_ip}";
   else
     logDebugResult FAILURE "failed";
@@ -172,11 +272,11 @@ function process_setup_file() {
 
   if isTrue ${_rescode}; then
     logDebug -n "Retrieving password from /etc/mysql/debian.cnf";
-    local _password="$(grep password /etc/mysql/debian.cnf  | head -n 1 | cut -d' ' -f 3)";
+    local _password="$(grep password /etc/mysql/debian.cnf | head -n 1 | cut -d' ' -f 3)";
     _rescode=$?;
 
     if isTrue ${_rescode}; then
-      logDebugResult SUCCESS "${_password}";
+      logDebugResult SUCCESS "success";
     else
       logDebugResult FAILURE "failed";
     fi
@@ -185,7 +285,6 @@ function process_setup_file() {
   if isTrue ${_rescode}; then
     logDebug -n "Replacing ___DEBIAN_SYS_MAINT_PASSWORD_HASH___ with ${_password} in ${_file}";
     sed -i "s ___DEBIAN_SYS_MAINT_PASSWORD_HASH___ ${_password} g" ${_file};
-    logDebugResult SUCCESS "done";
     _rescode=$?;
 
     if isTrue ${_rescode}; then
@@ -208,7 +307,21 @@ function install_mariadb_db() {
   local _dataDir="${1}";
   checkNotEmpty dataDir "${_dataDir}" 1;
 
-  mysql_install_db --datadir=${_dataDir};
+  createTempFile;
+  local _output="${RESULT}";
+
+  logInfo -n "Installing database in ${_dataDir}";
+  mysql_install_db --datadir=${_dataDir} > "${_output}" 2>&1;
+  local -i _rescode=$?;
+
+  if isTrue ${_rescode}; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "failed";
+    logInfoFile "${_output}";
+  fi
+
+  return ${_rescode};
 }
 
 # fun: start_mariadb dataDir user
@@ -225,9 +338,74 @@ function start_mariadb() {
   local _user="${2}";
   checkNotEmpty user "${_user}" 2;
 
+  createTempFile;
+  local _output="${RESULT}";
+
   logInfo -n "Starting MariaDB";
-  /usr/bin/mysqld_safe --nowatch --no-auto-restart --user=${_user} --datadir=${_dataDir};
-  logInfoResult SUCCESS "done";
+  /usr/bin/mysqld_safe --nowatch --no-auto-restart --user=${_user} --datadir=${_dataDir} > "${_output}" 2>&1;
+  local -i _rescode=$?;
+
+  if isTrue ${_rescode}; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "failed";
+    logInfoFile "${_output}";
+  fi
+
+  return ${_rescode};
+}
+
+# fun: sanitize_sql_file file
+# api: public
+# txt: Sanitizes given sql file.
+# opt: file: The sql file.
+# txt: Returns 0/TRUE if the operation suceeds; 1/FALSE otherwise.
+# txt: If the function returns 0/TRUE, the variable RESULT contains the sanitized file.
+# use: if sanitize_sql_file /usr/local/src/setup.sql; then echo "sql file sanitized"; fi
+function sanitize_sql_file() {
+  local _file="${1}";
+  checkNotEmpty file "${_file}" 1;
+
+  local -i _rescode=${FALSE};
+
+  logInfo -n "Sanitizing ${_file}";
+  createTempFile;
+  local _result="${RESULT}";
+  sed 's/@@global.server_uuid/UUID()/g' "${_file}" > "${_tempFile}";
+  _rescode=$?;
+  sed -i "s/@@master_info_repository/'unsupported'/g" "${_tempFile}";
+  local -i _aux=$?;
+  if isTrue ${_rescode}; then
+    _rescode=${_aux};
+  fi
+  sed -i "s/@@relay_log_info_repository/'unsupported'/g" "${_tempFile}";
+  _aux=$?;
+  if isTrue ${_rescode}; then
+    _rescode=${_aux};
+  fi
+  sed -i "s/SET v_has_ps_vars = IF(@@global.show_compatibility_56, 'NO', 'YES');/SET v_has_ps_vars = 'NO';/g" "${_tempFile}";
+  _aux=$?;
+  if isTrue ${_rescode}; then
+    _rescode=${_aux};
+  fi
+
+  sed -i "s|^\(...50001 VIEW .*memory_by_host_by_current_bytes.\).*||g" "${_tempFile}";
+  _aux=$?;
+  if isTrue ${_rescode}; then
+    _rescode=${_aux};
+  fi
+
+  if isTrue ${_rescode}; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "failed";
+  fi
+
+  if isTrue ${_rescode}; then
+    export RESULT="${_result}";
+  fi
+
+  return ${_rescode};
 }
 
 # fun: run_sql_file file password
@@ -245,23 +423,28 @@ function run_sql_file() {
 
   local -i _rescode=${FALSE};
 
+  createTempFile;
+  local _output="${RESULT}";
+
   if isEmpty "${_password}"; then
     logInfo -n "Running ${_file} as root with no password";
-    /usr/bin/mysql -u root < ${_file};
+    /usr/bin/mysql -u root -f < "${_file}" > "${_output}" 2>&1;
     _rescode=$?;
     if isTrue ${_rescode}; then
       logInfoResult SUCCESS "done";
     else
       logInfoResult FAILURE "failed";
+      logInfoFile "${_output}";
     fi
   else
     logInfo -n "Running ${_file} as root with password";
-    /usr/bin/mysql -u root --password="${_password}" < ${_file};
+    /usr/bin/mysql -u root --password="${_password}" -f < "${_file}" > "${_output}" 2>&1;
     _rescode=$?;
     if isTrue ${_rescode}; then
       logInfoResult SUCCESS "done";
     else
       logInfoResult FAILURE "failed";
+      logInfoFile "${_output}";
     fi
   fi
 
@@ -278,20 +461,54 @@ function upgrade_mariadb() {
   local _password="${1}";
   checkNotEmpty rootPassword "${_password}" 1;
 
-  mysql_upgrade -u root --password="${_password}"
+  createTempFile;
+  local _output="${RESULT}";
+
+  logInfo -n "Upgrading database";
+  mysql_upgrade -u root --password="${_password}" > "${_output}" 2>&1;
+  local -i _rescode=$?;
+  if isTrue ${_rescode}; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "failed";
+  fi
+
+  return ${_rescode};
 }
 
 # fun: shutdown_mariadb rootPassword
 # api: public
 # txt: Shuts down MySQL.
 # opt: rootPassword: The root password.
-# txt: Returns 0/TRUE if the database shutdown process starts; 1/FALSE otherwise.
+# txt: Returns 0/TRUE if the database shutdown process starts or it's already shut down; 1/FALSE otherwise.
 # use: if shutdown_mariadb "secret"; then echo "mysql shutting down"; fi
 function shutdown_mariadb() {
   local _password="${1}";
   checkNotEmpty rootPassword "${_password}" 1;
 
-  mysqladmin -u root --password="${_password}" -h127.0.0.1 --protocol=tcp shutdown 2> /dev/null
+  createTempFile;
+  local _output="${RESULT}";
+
+  local -i _rescode=${FALSE};
+
+  if is_mariadb_up; then
+    logInfo -n "Shutting database down";
+    mysqladmin -u root --password="${_password}" -h127.0.0.1 --protocol=tcp shutdown > "${_output}" 2>&1
+    if isTrue ${_rescode}; then
+      logInfoResult SUCCESS "done";
+    else
+      logInfoResult FAILURE "failed";
+      logInfoFile "${_output}";
+    fi
+  else
+    _rescode=${TRUE};
+  fi
+
+  if is_mariadb_up; then
+    _rescode=${TRUE};
+  fi
+
+  return ${_rescode};
 }
 
 # fun: process_data_folder dataDir user group
@@ -312,25 +529,47 @@ function process_data_folder() {
   local _group="${3}";
   checkNotEmpty group "${_group}" 3;
 
-  chown -R ${_user}:${_group} ${_dataDir} \
-  && chmod 755 ${_dataDir};
+  createTempFile;
+  local _output="${RESULT}";
+
+  logInfo -n "Processing ${_dataDir}";
+  chown -R ${_user}:${_group} ${_dataDir} > "${_output}" 2>&1 \
+    && chmod 755 ${_dataDir} >> "${_output}" 2>&1;
+  local -i _rescode=$?;
+  if isTrue ${_rescode}; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "failed";
+    logInfoFile "${_output}";
+  fi
+
+  return ${_rescode};
 }
 
-# fun: mark_db_as_bootstrapped dataDir markFile
+# fun: mark_db_as_bootstrapped markFile
 # api: public
 # txt: Marks the database installation as bootstrapped.
-# opt: dataDir: The data folder.
 # opt: markFile: The mark file.
 # txt: Returns 0/TRUE if the installation is marked as bootstrapped successfully; 1/FALSE otherwise.
-# use: if mark_db_as_bootstrapped /var/lib/mysql .bootstrapped; then echo "Database installation bootstrapped"; fi
+# use: if mark_db_as_bootstrapped /var/lib/mysql/.bootstrapped; then echo "Database installation bootstrapped"; fi
 function mark_db_as_bootstrapped() {
-  local _dataDir="${1}";
-  checkNotEmpty dataDir "${_dataDir}" 1;
+  local _markFile="${1}";
+  checkNotEmpty markFile "${_markFile}" 1;
 
-  local _markFile="${2}";
-  checkNotEmpty markFile "${_markFile}" 2;
+  createTempFile;
+  local _output="${RESULT}";
 
-  touch ${_dataDir}/"${_markFile}";
+  logInfo -n "Creating bootstrap mark ${_markFile}";
+  touch "${_markFile}" > "${_output}" 2>&1;
+  local -i _rescode=$?;
+  if isTrue ${_rescode}; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "failed";
+    logInfoFile "${_output}";
+  fi
+
+  return ${_rescode};
 }
 
 ## Script metadata and CLI settings.
@@ -339,9 +578,13 @@ setScriptDescription "Bootstraps a MariaDB server.";
 setScriptLicenseSummary "Distributed under the terms of the GNU General Public License v3";
 setScriptCopyright "Copyleft 2014-today Automated Computing Machinery S.L.";
 
-defineEnvVar SLEEP MANDATORY "The interval in seconds before checking if mysql is stopped" 10;
-defineEnvVar DATA_DIR MANDATORY "The folder with the db data" "/backup/${IMAGE}-db";
-defineEnvVar BOOTSTRAP_MARK_FILE MANDATORY "The file indicating the server has been already bootstrapped" ".bootstrapped";
-defineEnvVar BOOTSTRAP_SETUP_FILE MANDATORY "The file with the initial sql" "/usr/local/src/setup.sql";
-defineEnvVar BOOTSTRAP_SQL_FOLDER MANDATORY "The folder with the bootstrap SQL files" "/sql";
+defineEnvVar SLEEP OPTIONAL "The interval in seconds before checking if mysql is stopped" 10;
+defineEnvVar DATA_DIR OPTIONAL "The folder with the db data" "/backup/${IMAGE}-db";
+defineEnvVar BOOTSTRAP_SUCCESS_MARK_FILE OPTIONAL "The file indicating the server has been already bootstrapped successfully" "/remote/${IMAGE}/.bootstrapped";
+defineEnvVar BOOTSTRAP_FAILURE_MARK_FILE OPTIONAL "The file indicating the server couldn't be bootstrapped" "/remote/${IMAGE}/.bootstrap-failed";
+defineEnvVar BOOTSTRAP_SETUP_FILE OPTIONAL "The file with the initial sql" "/usr/local/src/setup.sql";
+defineEnvVar BOOTSTRAP_SQL_FOLDER OPTIONAL "The folder with the bootstrap SQL files" "/sql";
+defineEnvVar ROOT_PASSWORD OPTIONAL "The password of the root user" "${MARIADB_ROOT_PASSWORD}";
+defineEnvVar MARIADB_USER OPTIONAL "The system user" "${SERVICE_USER}";
+defineEnvVar MARIADB_GROUP OPTIONAL "The system group" "${SERVICE_GROUP}";
 # vim: syntax=sh ts=2 sw=2 sts=4 sr noet
diff --git a/mariadb/service.template b/mariadb/service.template
--- a/mariadb/service.template
+++ b/mariadb/service.template
@@ -23,23 +23,29 @@ function main() {
 
   logInfoResult SUCCESS "done";
 
-  bootstrap_if_not_already_bootstrapped;
+  if bootstrap_if_not_already_bootstrapped; then
 
-  setup_folder_permissions "${DATA_DIR}" "${SERVICE_USER}" "${SERVICE_GROUP}";
+    setup_folder_permissions "${DATA_DIR}" "${SERVICE_USER}" "${SERVICE_GROUP}";
 
-  logInfo -n "Synchronizing data";
-  sync_folders;
-  logInfoResult SUCCESS "done";
+    logInfo -n "Synchronizing data";
+    sync_folders;
+    logInfoResult SUCCESS "done";
 
-  if ! folderExists /var/run/mysql; then
-    mkdir /var/run/mysql;
+    if ! folderExists /var/run/mysql; then
+      mkdir /var/run/mysql;
+    fi
+    setup_folder_permissions /var/run/mysql "${SERVICE_USER}" "${SERVICE_GROUP}";
+
+    logInfo "Launching MariaDB";
+    launch_mysql "${SERVICE_USER}" "${ROOT_PASSWORD}" "${ENABLE_LOGSTASH}";
+
+    logInfo "Exiting";
+  else
+    logInfo "Bootstrap failed. Container halted.";
+    while isTrue ${TRUE}; do
+      sleep 100;
+    done
   fi
-  setup_folder_permissions /var/run/mysql "${SERVICE_USER}" "${SERVICE_GROUP}";
-
-  logInfo "Launching MariaDB";
-  launch_mysql "${SERVICE_USER}" "${MARIADB_ROOT_PASSWORD}" "${ENABLE_LOGSTASH}";
-
-  logInfo "Exiting";
 }
 
 # fun: already_bootstrapped dataDir markFile
@@ -62,27 +68,43 @@ function already_bootstrapped() {
 # fun: bootstrap_if_not_already_bootstrapped
 # api: public
 # txt: Bootstraps the server if not already bootstrapped.
-# txt: Returns 0/TRUE always.
-# use: bootstrap_if_not_already_bootstrapped
+# txt: Returns 0/TRUE if the bootstrap was already done, or it finished successfully; 1/FALSE otherwise.
+# use: if bootstrap_if_not_already_bootstrapped; then echo "Database bootstrapped"; fi
 function bootstrap_if_not_already_bootstrapped() {
+  local -i _rescode;
+
   logInfo -n "Checking if service already bootstrapped";
-  if fileExists "${BOOTSTRAP_MARK_FILE}"; then
+  if fileExists "${BOOTSTRAP_SUCCESS_MARK_FILE}"; then
     logInfoResult SUCCESS "already bootstrapped";
+    _rescode=${TRUE};
+  elif fileExists "${BOOTSTRAP_FAILURE_MARK_FILE}"; then
+    logInfoResult FAILURE "bootstrap failed";
+    _rescode=${FALSE};
   else
     logInfoResult SUCCESS "not bootstrapped";
 
     logInfo "Bootstrapping service ...";
     /usr/local/bin/bootstrap-db.sh
+    _rescode=$?;
 
-    while ! fileExists "${DATA_DIR}/${BOOTSTRAP_MARK_FILE}"; do
+    while  ! fileExists "${BOOTSTRAP_SUCCESS_MARK_FILE}" \
+        && ! fileExists "${BOOTSTRAP_FAILURE_MARK_FILE}"; do
       logInfo -n "Waiting ${SLEEP}s for the bootstrap process to finish";
       sleep ${SLEEP}
       logInfoResult SUCCESS "done";
     done
 
-    logInfo -n "Bootstrapping service";
-    logInfoResult SUCCESS "done";
+    logInfo -n "Checking if bootstrap finished successfully";
+    if fileExists "${BOOTSTRAP_SUCCESS_MARK_FILE}"; then
+      logInfoResult SUCCESS "done";
+      _rescode=${TRUE};
+    elif fileExists "${BOOTSTRAP_FAILURE_MARK_FILE}"; then
+      logInfoResult FAILURE "failed";
+      _rescode=${FALSE};
+    fi
   fi
+
+  return ${_rescode};
 }
 
 # fun: setup_folder_permissions
@@ -215,7 +237,8 @@ setScriptCopyright "Copyleft 2014-today Automated Computing Machinery S.L.";
 
 defineEnvVar SLEEP OPTIONAL "The interval in seconds before checking if mysql is stopped" 10;
 defineEnvVar DATA_DIR OPTIONAL "The folder with the db data" "/backup/${IMAGE}-db";
-defineEnvVar BOOTSTRAP_MARK_FILE OPTIONAL "The file indicating the server has been already bootstrapped" ".bootstrapped";
+defineEnvVar BOOTSTRAP_SUCCESS_MARK_FILE OPTIONAL "The file indicating the server has been already bootstrapped successfully" "/remote/${IMAGE}/.bootstrapped";
+defineEnvVar BOOTSTRAP_FAILURE_MARK_FILE OPTIONAL "The file indicating the server couldn't be bootstrapped" "/remote/${IMAGE}/.bootstrap-failed";
 defineEnvVar BOOTSTRAP_SETUP_FILE OPTIONAL "The file with the initial sql" "/usr/local/src/setup.sql";
 defineEnvVar BOOTSTRAP_SQL_FOLDER OPTIONAL "The folder with the bootstrap SQL files" "/sql";
 defineEnvVar INNODB_BUFFER_POOL_SIZE_FACTOR OPTIONAL "The default pool size factor for InnoDB" "${DEFAULT_INNODB_BUFFER_POOL_SIZE_FACTOR}";
@@ -224,5 +247,6 @@ defineEnvVar ENABLE_STRICT_MODE OPTIONAL "Whether to enable strict mode" ${DEFAU
 defineEnvVar ENABLE_STRICT_MODE_CONFIG_FILE OPTIONAL "The location of the config file to enable strict mode" "${DEFAULT_ENABLE_STRICT_MODE_CONFIG_FILE}";
 defineEnvVar ENABLE_LOCAL_INFILE OPTIONAL "Whether to enable LOAD DATA LOCAL INFILE" ${DEFAULT_ENABLE_LOCAL_INFILE};
 defineEnvVar ENABLE_LOCAL_INFILE_CONFIG_FILE OPTIONAL "The location of the config file to enable LOAD DATA LOCAL INFILE" "${DEFAULT_ENABLE_LOCAL_INFILE_CONFIG_FILE}";
+defineEnvVar ROOT_PASSWORD OPTIONAL "The root password" "${SQ_MARIADB_ROOT_PASSWORD}";
 # vim: syntax=sh ts=2 sw=2 sts=4 sr noet
 
