Base image now customizes the timezone and locale.
Additionally, it can launch an NTP daemon if enabled.

diff --git a/base/dry-wit b/base/dry-wit
--- a/base/dry-wit
+++ b/base/dry-wit
@@ -16,8 +16,9 @@
 #    You should have received a copy of the GNU General Public License
 #    along with dry-wit.  If not, see <http://www.gnu.org/licenses/>.
 
-set -o errexit  # terminate on any unhandled error
-set -o nounset  # terminate on any unset variable
+#set -o errexit  # terminate on any unhandled error
+## TODO: fix color stuff
+#set -o nounset  # terminate on any unset variable
 set -o pipefail # In a pipe, the exit status of the last command that threw a non-zero exit code is returned.
 #set -o xtrace   # trace what gets executed
 
@@ -55,7 +56,11 @@ export UNDEFINED=255;
 
 export _DRY_WIT_LOG_STACK=();
 export _DRY_WIT_LOG_CATEGORY_STACK=();
+export LOG_CATEGORY_NAMESPACE="";
 export _DRY_WIT_LOG_LEVEL_STACK=();
+export _DRY_WIT_LOG_TRACE=${FALSE};
+export _DRY_WIT_LOG_DEBUG=${FALSE};
+export _DRY_WIT_LOG_INFO=${TRUE};
 export _DRY_WIT_LOG_OUTCOME_TOKENS=();
 export _DRY_WIT_LOG_OUTCOME_COLORS=();
 export _DRY_WIT_DEFAULT_TERM_WIDTH=80;
@@ -105,13 +110,13 @@ function isDefined() {
 ## Example:
 ##   if isDefined "${MYVAR}"; then echo "MYVAR is defined"; fi
 function isVariableDefined() {
-    local _rescode;
-    set +o nounset  # terminate on any unset variable
-    eval "[ -v \${$1} ] 2> /dev/null"
-    _rescode=$?;
-    set -o nounset  # terminate on any unset variable
+  local _rescode;
+  set +o nounset  # allow unset variables
+  eval "[ -v \${$1} ] 2> /dev/null"
+  _rescode=$?;
+  # TODO set -o nounset  # terminate on any unset variable
 
-    return ${_rescode};
+  return ${_rescode};
 }
 
 ## PRIVATE/DEBUG
@@ -244,7 +249,7 @@ function _isEnvVarDefined() {
   IFS=$' \t\n';
   set +o nounset
   for e in ${#ENV_VARIABLES[@]}; do [[ "${e}" == "${_varName}" ]] && return 0; done
-  set -o nounset
+  # TODO set -o nounset
   IFS="${_oldIFS}";
   return 1;
 }
@@ -600,7 +605,13 @@ function appendEnvVariable() {
 function addFileToCleanup() {
   local _file="${1}";
   #  logTrace "Appending ${result} to _CLEANUP_FILES";
-  appendItemToArray "${_file}" _CLEANUP_FILES;
+
+  if declare -p _CLEANUP_FILES > /dev/null 2>&1; then
+    upvars -a$((${#_CLEANUP_FILES[@]}+1)) _CLEANUP_FILES "${_CLEANUP_FILES[@]}" "${_file}";
+  else
+    export -a _CLEANUP_FILES=();
+    upvars -a1 _CLEANUP_FILES "${_file}";
+  fi
 
 #  local _oldIFS="${IFS}";
 #  IFS=$' \t\n';
@@ -760,6 +771,7 @@ function printErrorMessage() {
 
   local _oldIFS="${IFS}";
   IFS=$' \t\n';
+  set +o nounset  # allow unset variables
   for i in ${BUILTIN_ERRORS[@]}; do
     _result=$((_result+1));
     if [ "x${i}" == "x${1}" ]; then
@@ -767,11 +779,12 @@ function printErrorMessage() {
       break;
     fi;
   done
+  # TODO set -o nounset  # disallow unset variables
 
   if [ "x${_message}" == "x" ]; then
     # IFS issue
 #    _result=${TRUE};
-    for i in ${ERROR_MESSAGES[*]}; do
+    for i in ${ERROR_MESSAGES[@]}; do
       _result=$((_result+1));
       if [ "x${i}" == "x${1}" ]; then
         _message="$i";
@@ -2917,8 +2930,9 @@ function checkDependency() {
     _errorCode="${RESULT}";
   fi
 
-  which ${_req} > /dev/null 2&>1;
-  [ $? -ne ${TRUE} ] && exitWithErrorCode ${_errorCode};
+  which ${_req} > /dev/null 2>&1;
+  _rescode=$?;
+  [ ${_rescode} -ne ${TRUE} ] && exitWithErrorCode ${_errorCode};
 }
 
 ## Performs the checks for a required dependency.
@@ -2938,7 +2952,6 @@ function checkReq() {
 ## Checks dry-wit's own requirements.
 function _defineDryWitRequirements() {
   checkReq grep;
-  checkReq mapfile;
   checkReq mktemp;
 }
 
@@ -2985,9 +2998,9 @@ function _parseCommonInput() {
 ## -> 1: The file or folder.
 ## <- RESULT: The id of the user that owns the file or folder.
 ## Example:
-##   retrieve_uid /tmp
+##   retrieveOwnerUid /tmp
 ##   echo "The id of the owner of /tmp is ${RESULT}";
-function retrieve_owner_uid() {
+function retrieveOwnerUid() {
   local _file="${1}"
   local _result;
 
@@ -3000,9 +3013,9 @@ function retrieve_owner_uid() {
 ## -> 1: The file or folder.
 ## <- RESULT: The id of the group that owns the file or folder.
 ## Example:
-##   retrieve_uid /tmp
+##   retrieveOwnerGid /tmp
 ##   echo "The id of the group of /tmp is ${RESULT}";
-function retrieve_owner_gid() {
+function retrieveOwnerGid() {
   local _file="${1}"
   local _result;
 
@@ -3016,10 +3029,10 @@ function retrieve_owner_gid() {
 ## <- 0/${TRUE} if it exists; 1/${FALSE} otherwise.
 ##
 ## Example:
-##   if uid_already_exists 1; then
+##   if uidAlreadyExists 1; then
 ##     echo "User 1 exists";
 ##   fi
-function uid_already_exists() {
+function uidAlreadyExists() {
   local _uid="${1}";
   local _rescode;
 
@@ -3041,10 +3054,10 @@ function uid_already_exists() {
 ## <- 0/${TRUE} if it exists; 1/${FALSE} otherwise.
 ##
 ## Example:
-##   if gid_already_exists 103; then
+##   if gidAlreadyExists 103; then
 ##     echo "Group 103 exists";
 ##   fi
-function gid_already_exists() {
+function gidAlreadyExists() {
   local _gid="${1}";
   local _rescode;
 
@@ -3066,10 +3079,10 @@ function gid_already_exists() {
 ## <- 0/${TRUE} if it exists; 1/${FALSE} otherwise.
 ##
 ## Example:
-##   if user_already_exists guest; then
+##   if userAlreadyExists guest; then
 ##     echo "User guest exists";
 ##   fi
-function user_already_exists() {
+function userAlreadyExists() {
   local _user="${1}";
   local _rescode;
 
@@ -3091,10 +3104,10 @@ function user_already_exists() {
 ## <- 0/${TRUE} if it exists; 1/${FALSE} otherwise.
 ##
 ## Example:
-##   if group_already_exists users; then
+##   if groupAlreadyExists users; then
 ##     echo "Group users exists";
 ##   fi
-function group_already_exists() {
+function groupAlreadyExists() {
   local _group="${1}";
   local _rescode;
 
@@ -3116,9 +3129,9 @@ function group_already_exists() {
 ## <- RESULT: The user id.
 ##
 ## Example:
-##   retrieve_user_from_uid "1";
+##   retrieveUserFromUid "1";
 ##   echo "The name of user 1 is ${RESULT}";
-function retrieve_user_from_uid() {
+function retrieveUserFromUid() {
   local _uid="${1}";
   local _result;
   local _rescode;
@@ -3136,9 +3149,9 @@ function retrieve_user_from_uid() {
 ## <- RESULT: The group id.
 ##
 ## Example:
-##   retrieve_group_from_gid "100";
+##   retrieveGroupFromGid "100";
 ##   echo "The name of group 1 is ${RESULT}";
-function retrieve_group_from_gid() {
+function retrieveGroupFromGid() {
   local _gid="${1}";
   local _result;
   local _rescode;
@@ -3158,9 +3171,9 @@ function retrieve_group_from_gid() {
 ## <- RESULT: The user name.
 ##
 ## Example:
-##   retrieve_uid_from_user "root";
+##   retrieveUidFromUser "root";
 ##   echo "The name of user root is ${RESULT}";
-function retrieve_uid_from_user() {
+function retrieveUidFromUser() {
   local _user="${1}";
   local _result;
   local _rescode;
@@ -3183,9 +3196,9 @@ function retrieve_uid_from_user() {
 ## <- RESULT: The group name.
 ##
 ## Example:
-##   retrieve_gid_from_group "admin";
+##   retrieveGidFromGroup "admin";
 ##   echo "The name of group admin is ${RESULT}";
-function retrieve_gid_from_group() {
+function retrieveGidFromGroup() {
   local _group="${1}";
   local _result;
   local _rescode;
@@ -3208,10 +3221,10 @@ function retrieve_gid_from_group() {
 ## <- 0/${TRUE} if the user gets created successfully; 1/${FALSE} otherwise.
 ##
 ## Example:
-## if create_user "fakeuser"; then
+## if createUser "fakeuser"; then
 ##    echo "fakeuser created successfully";
 ## fi
-function create_user() {
+function createUser() {
   local _userName="${1}";
   local _rescode;
 
@@ -3233,10 +3246,10 @@ function create_user() {
 ## <- 0/${TRUE} if the group gets created successfully; 1/${FALSE} otherwise.
 ##
 ## Example:
-## if create_group "fakegroup"; then
+## if createGroup "fakegroup"; then
 ##    echo "fakegroup created successfully";
 ## fi
-function create_group() {
+function createGroup() {
   local _groupName="${1}";
   local _rescode;
 
@@ -3258,10 +3271,10 @@ function create_group() {
 ## <- 0/${TRUE} if the user is removed successfully; 1/${FALSE} otherwise.
 ##
 ## Example:
-## if delete_user "fakeuser"; then
+## if deleteUser "fakeuser"; then
 ##    echo "fakeuser deleted successfully";
 ## fi
-function delete_user() {
+function deleteUser() {
   local _userName="${1}";
   local _rescode;
 
@@ -3283,10 +3296,10 @@ function delete_user() {
 ## <- 0/${TRUE} if the group is removed successfully; 1/${FALSE} otherwise.
 ##
 ## Example:
-## if delete_group "fakegroup"; then
+## if deleteGroup "fakegroup"; then
 ##    echo "fakegroup deleted successfully";
 ## fi
-function delete_group() {
+function deleteGroup() {
   local _groupName="${1}";
   local _rescode;
 
@@ -3309,8 +3322,8 @@ function delete_group() {
 ## -> 3: the folder.
 ## -> 4+: the command.
 ## Example:
-##  run_command_as_uid_gid 1000 100 /tmp "ls -ltrhia"
-function run_command_as_uid_gid() {
+##  runCommandAsUidGid 1000 100 /tmp "ls -ltrhia"
+function runCommandAsUidGid() {
   local _user="${1}";
   local _uid="${2}";
   local _gid="${3}";
@@ -3342,6 +3355,98 @@ EOF
   chpst -u ${SERVICE_USER}:${SERVICE_GROUP} -U ${SERVICE_USER}:${SERVICE_GROUP} ${_runme}
 }
 
+## Updates the uid of the user.
+## -> 1: The user.
+## -> 2: The uid.
+## <- 0/${TRUE} if the user's uid is updated successfully; 1/${FALSE} otherwise.
+## Example:
+## updateUserUid "guest" 1001
+function updateUserUid() {
+  local _user="${1}";
+  local _uid="${2}";
+  local _rescode;
+
+  logInfo -n "Changing ${_user}'s uid to ${_uid}";
+  usermod -u ${_uid} ${_user} > /dev/null 2>&1
+  _rescode=$?;
+  if [ ${_rescode} -eq ${TRUE} ]; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "failed";
+    exitWithErrorCode CANNOT_CHANGE_UID "${_user}";
+  fi
+
+  return ${_rescode};
+}
+
+## Updates the gid of the user.
+## -> 1: The user.
+## -> 2: The gid.
+## <- 0/${TRUE} if the user's gid is updated successfully; 1/${FALSE} otherwise.
+## Example:
+## updateUserGid "guest" 103
+function updateUserGid() {
+  local _user="${1}";
+  local _gid="${2}";
+  local _rescode;
+
+  logInfo -n "Changing ${_user}'s primary group as ${_gid}";
+  usermod -g ${_gid} ${_user} > /dev/null 2>&1
+  _rescode=$?;
+  if [ ${_rescode} -eq ${TRUE} ]; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "unneeded";
+  fi
+
+  return ${_rescode};
+}
+
+## Updates the gid of the group.
+## -> 1: The group.
+## -> 2: The gid.
+## <- 0/${TRUE} if the group's gid is updated successfully; 1/${FALSE} otherwise.
+##
+## Example:
+## updateUserGid "guests" 103
+function updateGroupGid() {
+  local _group="${1}";
+  local _gid="${2}";
+  local _rescode;
+
+  logInfo -n "Changing ${_group}'s gid to ${_gid}";
+  groupmod -g ${_gid} ${_group} > /dev/null 2>&1
+  _rescode=$?;
+  if [ ${_rescode} -eq ${TRUE} ]; then
+    logInfoResult SUCCESS "done";
+  else
+    logInfoResult FAILURE "failed";
+    exitWithErrorCode CANNOT_CHANGE_GID "${_group}";
+  fi
+
+  return ${_rescode};
+}
+
+## Adds given user to a group.
+## -> 1: The user.
+## -> 2: The group.
+## <- 0/${TRUE} if the user gets added to the group successfully; 1/${FALSE} otherwise.
+##
+## Example:
+##   if addUserToGroup guest users; then
+##     echo "User guest added to group users";
+##   fi
+function addUserToGroup() {
+  local _user="${1}";
+  local _group="${2}";
+  local _rescode;
+
+  gpasswd -a ${_user} ${_group} > /dev/null;
+  _rescode=$?;
+
+  return ${_rescode};
+}
+
 ## Checks input common to all scripts.
 function _checkCommonInput() {
 
@@ -3362,13 +3467,12 @@ function _checkScript() {
   logTrace -n "Checking mandatory constants";
   local _oldIFS="${IFS}";
   IFS=$' \t\n';
-  for v in ERROR_MESSAGES; do
-    if [ "x${v}" == "x" ]; then
+  for v in ${ERROR_MESSAGES[@]}; do
+    if [ -z "${v}" ]; then
       exitWithErrorCode MISSING_MANDATORY_VARIABLES $v;
     fi
   done
   logTraceResult SUCCESS "Done";
-
   logTrace -n "Checking mandatory functions";
   for f in usage main; do
     _functionPresent $f $_script;
@@ -3488,7 +3592,7 @@ function _main() {
 # NOTE: For assigning multiple variables, use 'upvars'.  Do NOT
 #       use multiple 'upvar' calls, since one 'upvar' call might
 #       reassign a variable to be used by another 'upvar' call.
-# Example: 
+# Example:
 #
 #    f() { local b; g b; echo $b; }
 #    g() { local "$1" && upvar $1 bar; }
@@ -3506,7 +3610,7 @@ upvar() {
 
 
 # Assign variables one scope above the caller
-# Usage: local varname [varname ...] && 
+# Usage: local varname [varname ...] &&
 #        upvars [-v varname value] | [-aN varname [value ...]] ...
 # Available OPTIONS:
 #     -aN  Assign next N values to varname as array
