Added missing entries in .gitignore

diff --git a/base/dry-wit b/base/dry-wit
--- a/base/dry-wit
+++ b/base/dry-wit
@@ -2972,12 +2972,12 @@ function uncompress() {
   fi
 
   if [ ${_result} == 0 ]; then
-    logDebug -n "Uncompressing ${_file}";
+    logInfo -n "Uncompressing ${_file}";
     tar ${_flags} "${_file}" -C "${_destination}" 2>&1 > "${_errorOutput}";
     if [ $? == 0 ]; then
-      logDebugResult "Done";
+      logInfoResult "Done";
     else
-      logDebugResult "Failed";
+      logInfoResult "Failed";
       logDebugFile "${_errorOutput}";
       _result=2;
     fi
@@ -3614,7 +3614,6 @@ function createUser() {
 
 ## Creates a new group.
 ## -> 1: The group name.
-## -> 2: The group id (optional).
 ## <- 0/${TRUE} if the group gets created successfully; 1/${FALSE} otherwise.
 ##
 ## Example:
@@ -3624,19 +3623,13 @@ function createUser() {
 function createGroup() {
   local _groupName="${1}";
   checkNotEmpty "group" "${_groupName}" 1;
-  local _gid="${2}";
 
   local _rescode;
 
   logDebug -n "Creating group ${_groupName}";
 
-  if isEmpty "${_gid}"; then
-    groupadd "${_groupName}";
-    _rescode=$?;
-  else
-    groupadd -g "${_gid}" "${_groupName}";
-    _rescode=$?;
-  fi
+  groupadd "${_groupName}";
+  _rescode=$?;
   if isTrue ${_rescode}; then
     logDebugResult SUCCESS "done";
   else
@@ -3779,13 +3772,13 @@ function updateUserUid() {
 
   local _rescode;
 
-  logDebug -n "Changing ${_user}'s uid to ${_uid}";
+  logInfo -n "Changing ${_user}'s uid to ${_uid}";
   usermod -u ${_uid} ${_user} > /dev/null 2>&1
   _rescode=$?;
   if isTrue ${_rescode}; then
-    logDebugResult SUCCESS "done";
+    logInfoResult SUCCESS "done";
   else
-    logDebugResult FAILURE "failed";
+    logInfoResult FAILURE "failed";
     usermod -u ${_uid} ${_user} 2>&1
   fi
 
@@ -3806,14 +3799,13 @@ function updateUserGid() {
   checkNotEmpty "gid" "${_gid}" 2;
   local _rescode;
 
-  logDebug -n "Changing ${_user}'s primary group to ${_gid}";
+  logInfo -n "Changing ${_user}'s primary group to ${_gid}";
   usermod -g ${_gid} ${_user} > /dev/null 2>&1
   _rescode=$?;
   if isTrue ${_rescode}; then
-    logDebugResult SUCCESS "done";
+    logInfoResult SUCCESS "done";
   else
-    logDebugResult FAILURE "unneeded";
-    usermod -g ${_gid} ${_user} 2>&1
+    logInfoResult FAILURE "unneeded";
   fi
 
   return ${_rescode};
@@ -3831,13 +3823,13 @@ function updateGroupGid() {
   local _gid="${2}";
   local _rescode;
 
-  logDebug -n "Changing ${_group}'s gid to ${_gid}";
+  logInfo -n "Changing ${_group}'s gid to ${_gid}";
   groupmod -g ${_gid} ${_group} > /dev/null 2>&1
   _rescode=$?;
   if isTrue ${_rescode}; then
-    logDebugResult SUCCESS "done";
+    logInfoResult SUCCESS "done";
   else
-    logDebugResult FAILURE "failed";
+    logInfoResult FAILURE "failed";
     groupmod -g ${_gid} ${_group} 2>&1
   fi
 
