Added support to disable built-in services.
- Updated some images according to new base image.
- Initial work on mariadb-bootstrap.

diff --git a/base/my_exec b/base/my_exec
--- a/base/my_exec
+++ b/base/my_exec
@@ -1,8 +1,11 @@
 #!/bin/bash
 
-function run_help() {
-  /usr/local/bin/help
-}
+if [ ! -e /README ]; then
+    echo "Error: This image should include a README file."
+    exit 1
+fi
+
+source /etc/my_exec.d/*
 
 trap 'run_help' ERR
 
