Lots of accumulated changes in a number of repositories.

diff --git a/postgresql-bootstrap/service b/postgresql-bootstrap/service
--- a/postgresql-bootstrap/service
+++ b/postgresql-bootstrap/service
@@ -4,7 +4,7 @@
 
 function usage() {
 cat <<EOF
-docker run -it --link [postgres]:db -v [folder]:/sql [-v[v]|-q|--quiet] [-u|--user] user [-p|--password] password [[-db|--database] database]? [[-f|--file] file]?
+docker run -it --link [postgres]:db -v [folder]:/sql [-v[v]|-q|--quiet] [-F|--force] [-u|--user] user [-p|--password] password [[-db|--database] database]? [[-f|--file] file]?
 $SCRIPT_NAME [-h|--help]
 (c) 2015-today Automated Computing Machinery S.L.
     Distributed under the terms of the GNU General Public License v3
@@ -16,6 +16,7 @@ Where:
   * -p | --password: the database password.
   * -db | --database: The database name. Defaults to "${DEFAULT_DB_NAME}".
   * -f | --file: the input file. Optional. If not specified, all files in the mounted /sql volume will be used as input.
+  * -F | --force: whether to force processing given file(s).
 Common flags:
     * -h | --help: Display this message.
     * -v: Increase the verbosity.
@@ -40,7 +41,7 @@ function defineErrors() {
   export NO_DB_USER_SPECIFIED="The database user cannot be empty";
   export NO_DB_NAME_SPECIFIED="The database name cannot be empty";
   export NO_SQL_FOLDER_SPECIFIED="The SQL folder is mandatory";
-  export NO_SQL_FILES_FOUND="No SQL files found in ${SQL_FOLDER}";
+  export NO_SQL_FILES_FOUND="No SQL files found in ${SQL_FOLDER:-${DEFAULT_SQL_FOLDER}}";
   export SQL_FILE_NOT_FOUND="The specified file does not exist";
   export SQL_FILE_NOT_READABLE="The specified file is not readable";
   export SQL_FILE_IS_NOT_A_FILE="The specified file is not a file";
@@ -77,24 +78,28 @@ function parseInput() {
       -h | --help | -v | -vv | -q)
          shift;
          ;;
+      -F | --force)
+         export FORCE_FLAG=${TRUE}
+         shift;
+         ;;
       -u | --user)
          shift;
-         DB_USER="${1}";
+         export DB_USER="${1}";
          shift;
          ;;
       -p | --password)
          shift;
-         DB_PASSWORD="${1}";
+         export DB_PASSWORD="${1}";
          shift;
          ;;
       -db | --database)
          shift;
-         DB_NAME="${1}";
+         export DB_NAME="${1}";
          shift;
          ;;
       -f | --file)
          shift;
-         SQL_FILE="${1}";
+         export SQL_FILE="${1}";
          shift;
          ;;
     esac
@@ -108,10 +113,8 @@ function parseInput() {
     DB_NAME="${DEFAULT_DB_NAME}";
   fi
 
-  # Parameters
   if [[ -z ${SQL_FOLDER} ]]; then
-    SQL_FOLDER="$1";
-    shift;
+    SQL_FOLDER="${DEFAULT_SQL_FOLDER}";
   fi
 }
 
@@ -128,7 +131,7 @@ function checkInput() {
   for _flag in ${_flags}; do
     _flagCount=$((_flagCount+1));
     case ${_flag} in
-      -h | --help | -v | -vv | -q | --quiet | -u | --user | -p | --password | -db | --database | -f | --file)
+      -h | --help | -v | -vv | -q | --quiet | -u | --user | -p | --password | -db | --database | -f | --file | -F | --force)
          ;;
       *) logDebugResult FAILURE "fail";
          exitWithErrorCode INVALID_OPTION ${_flag};
@@ -147,30 +150,41 @@ function checkInput() {
   fi
 
   if [[ -z ${SQL_FOLDER} ]]; then
-    if [[ -z ${SQL_FILE} ]]; then
-      logDebugResult FAILURE "fail";
-      exitWithErrorCode NO_SQL_FOLDER_SPECIFIED;
-    else
-      if [[ -e ${SQL_FILE} ]]; then
-        if [[ -r ${SQL_FILE} ]]; then
-          if [[ -f ${SQL_FILE} ]]; then
-            logDebugResult SUCCESS "valid";
-          else
-            logDebugResult FAILURE "fail";
-            exitWithErrorCode SQL_FILE_IS_NOT_A_FILE;
-          fi
+    logDebugResult FAILURE "fail";
+    exitWithErrorCode NO_SQL_FOLDER_SPECIFIED;
+  fi
+
+  if [[ -n ${SQL_FILE} ]]; then
+    if [[ ! -e ${SQL_FILE} ]]; then
+      SQL_FILE="${SQL_FOLDER}/${SQL_FILE}";
+    fi
+
+    if [[ -e ${SQL_FILE} ]]; then
+      if [[ -r ${SQL_FILE} ]]; then
+        if [[ -f ${SQL_FILE} ]]; then
+          logDebugResult SUCCESS "valid";
         else
           logDebugResult FAILURE "fail";
-          exitWithErrorCode SQL_FILE_NOT_READABLE;
+          exitWithErrorCode SQL_FILE_IS_NOT_A_FILE ${SQL_FILE};
         fi
       else
         logDebugResult FAILURE "fail";
-        exitWithErrorCode SQL_FILE_NOT_FOUND;
+        exitWithErrorCode SQL_FILE_NOT_READABLE ${SQL_FILE};
       fi
+    else
+      logDebugResult FAILURE "fail";
+      exitWithErrorCode SQL_FILE_NOT_FOUND ${SQL_FILE};
     fi
-  else
-    logDebugResult SUCCESS "valid";
   fi
+
+  logDebugResult SUCCESS "valid";
+}
+
+## Checks whether the -f or --force flag is enabled.
+## Example:
+##   if force_mode_enabled; then [..]; fi
+function force_mode_enabled() {
+  _flagEnabled FORCE_MODE;
 }
 
 ## Checks whether given SQL file is marked as processed.
@@ -182,13 +196,16 @@ function checkInput() {
 function is_sql_file_marked_as_processed() {
   local _folder="${1}";
   local _file="${2}";
-  local _rescode=0;
-  if [ -e "${_folder}"/."${_file}".done ]; then
-    _rescode=0;
+  local _rescode;
+
+  if    force_mode_enabled \
+     && [ -e "${_folder}"/."${_file}".done ]; then
+    _rescode=${TRUE};
   else
-    _rescode=1;
+    _rescode=${FALSE};
   fi
-  return $?;
+
+  return ${_rescode};
 }
 
 ## Marks given SQL file as processed.
@@ -200,8 +217,16 @@ function is_sql_file_marked_as_processed() {
 function mark_sql_file_as_processed() {
   local _folder="${1}";
   local _file="${2}";
-  touch "${_folder}"/."${_file}".done 2> /dev/null
-  return $?;
+  local _rescode=${TRUE};
+
+  if force_mode_enabled; then
+    touch "${_folder}"/."${_file}".done 2> /dev/null
+    _rescode=$?;
+  else
+    _rescode=${TRUE};
+  fi
+
+  return ${_rescode};
 }
 
 ## Finds the SQL files in given folder.
@@ -282,13 +307,13 @@ function main() {
 
   if [[ -n ${SQL_FILE} ]]; then
     _atLeastOneFile=${TRUE};
-    process_sql_file "${SQL_FOLDER}/${SQL_FILE}";
+    process_sql_file "${SQL_FILE}";
   else
     find_sql_files "${SQL_FOLDER}";
     _sqlFiles="${RESULT}";
     for _file in ${_sqlFiles}; do
       _atLeastOneFile=${TRUE};
-      process_sql_file "${SQL_FOLDER}/${_file}";
+      process_sql_file "${_file}";
     done
     if [ ${_atLeastOneFile} -ne ${TRUE} ]; then
       exitWithErrorCode NO_SQL_FILES_FOUND;
